# Generated by Django 5.2.3 on 2025-06-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeWebsite', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='briefcase', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
